export const pseudoClasses = {
  active: 'pseudoClass',
  anyLink: 'pseudoClass',
  checked: 'pseudoClass',
  default: 'pseudoClass',
  defined: 'pseudoClass',
  disabled: 'pseudoClass',
  empty: 'pseudoClass',
  enabled: 'pseudoClass',
  first: 'pseudoClass',
  firstChild: 'pseudoClass',
  firstOfType: 'pseudoClass',
  fullscreen: 'pseudoClass',
  focus: 'pseudoClass',
  focusVisible: 'pseudoClass',
  focusWithin: 'pseudoClass',
  host: 'pseudoClass',
  hover: 'pseudoClass',
  indeterminate: 'pseudoClass',
  inRange: 'pseudoClass',
  invalid: 'pseudoClass',
  lastChild: 'pseudoClass',
  lastOfType: 'pseudoClass',
  left: 'pseudoClass',
  link: 'pseudoClass',
  onlyChild: 'pseudoClass',
  onlyOfType: 'pseudoClass',
  optional: 'pseudoClass',
  outOfRange: 'pseudoClass',
  placeholderShown: 'pseudoClass',
  readOnly: 'pseudoClass',
  readWrite: 'pseudoClass',
  required: 'pseudoClass',
  right: 'pseudoClass',
  root: 'pseudoClass',
  scope: 'pseudoClass',
  target: 'pseudoClass',
  valid: 'pseudoClass',
  visited: 'pseudoClass',
};

export const pseudoClassesParam = {
  dir: 'pseudoClassParam',
  host: 'pseudoClassParam',
  hostContext: 'pseudoClassParam',
  lang: 'pseudoClassParam',
  not: 'pseudoClassParam',
  nthChild: 'pseudoClassParam',
  nthLastChild: 'pseudoClassParam',
  nthLastOfType: 'pseudoClassParam',
  nthOfType: 'pseudoClassParam',
};
